const projects = [
    { 
        pId: "1", 
        category: "Development",
        title: "Tatak Lokal",
        shortdesc: "",
        description:"", 
        liveLink:"", 
        prevLink:"", 
        nextLink:"", 
        image:"/images/projects/tataklokal.png", 
        image1:"", 
        image2:"", 
        image3:"", 
        image4:"", 
        image5:""
    },
    { 
        pId: "2", 
        category: "Design",
        title: "Tatak Lokal",
        shortdesc: "",
        description:"", 
        liveLink:"", 
        prevLink:"", 
        nextLink:"", 
        image:"/images/projects/tataklokal.png", 
        image1:"", 
        image2:"", 
        image3:"", 
        image4:"", 
        image5:""
    },
    { 
        pId: "2", 
        category: "Design",
        title: "Tatak Lokal",
        shortdesc: "",
        description:"", 
        liveLink:"", 
        prevLink:"", 
        nextLink:"", 
        image:"/images/projects/tataklokal.png", 
        image1:"", 
        image2:"", 
        image3:"", 
        image4:"", 
        image5:""
    },
    { 
        pId: "2", 
        category: "Design",
        title: "Tatak Lokal",
        shortdesc: "",
        description:"", 
        liveLink:"", 
        prevLink:"", 
        nextLink:"", 
        image:"/images/projects/tataklokal.png", 
        image1:"", 
        image2:"", 
        image3:"", 
        image4:"", 
        image5:""
    },
]

export default projects;