const projects = [
    { 
        pId: "1", 
        category: "Development",
        title: "Tatak Lokal",
        shortdesc: "This is a sample short description.",
        date:"January 22, 2024", 
        description:"This is a sample short description. This is a sample short description. This is a sample short description.",
        liveLink:"", 
        prevLink:"", 
        nextLink:"", 
        image:"/images/projects/tataklokal.png", 
        image1:"", 
        image2:"", 
        image3:"", 
        image4:"", 
        image5:""
    },
    { 
        pId: "2", 
        category: "Development",
        title: "Tatak Lokal - Web App",
        shortdesc: "",
        date:"", 
        description:"", 
        liveLink:"", 
        prevLink:"", 
        nextLink:"", 
        image:"/images/projects/tataklokal.png", 
        image1:"", 
        image2:"", 
        image3:"", 
        image4:"", 
        image5:""
    },
    { 
        pId: "3", 
        category: "Development",
        title: "MNHS | LMS - Web App",
        shortdesc: "",
        date:"", 
        description:"", 
        liveLink:"", 
        prevLink:"", 
        nextLink:"", 
        image:"/images/projects/mnhs.png", 
        image1:"", 
        image2:"", 
        image3:"", 
        image4:"", 
        image5:""
    },
    { 
        pId: "4", 
        category: "Development",
        title: "Baumman Fit Box - WordPress",
        shortdesc: "",
        date:"", 
        description:"", 
        liveLink:"", 
        prevLink:"", 
        nextLink:"", 
        image:"/images/projects/baumann.jpg", 
        image1:"", 
        image2:"", 
        image3:"", 
        image4:"", 
        image5:""
    },
    { 
        pId: "5", 
        category: "Development",
        title: "Spin The Wheel - Web App",
        shortdesc: "",
        date:"", 
        description:"", 
        liveLink:"", 
        prevLink:"", 
        nextLink:"", 
        image:"/images/projects/wheel.png", 
        image1:"", 
        image2:"", 
        image3:"", 
        image4:"", 
        image5:""
    },
    { 
        pId: "6", 
        category: "Design",
        title: "Baumman Fit Box - WordPress",
        shortdesc: "",
        date:"", 
        description:"", 
        liveLink:"", 
        prevLink:"", 
        nextLink:"", 
        image:"/images/projects/tataklokal.png", 
        image1:"", 
        image2:"", 
        image3:"", 
        image4:"", 
        image5:""
    },
]

export default projects;